# Generated by Django 2.2.1 on 2019-05-18 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='skills',
            field=models.ManyToManyField(blank=True, to='App.Skill'),
        ),
    ]
