# Generated by Django 2.2 on 2019-05-19 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='icon',
            field=models.ImageField(default=None, upload_to=''),
        ),
    ]
