# Generated by Django 2.2 on 2019-05-19 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_organization_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='icon',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=''),
        ),
    ]
