# Generated by Django 2.2 on 2019-05-18 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_auto_20190518_2056'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='blurb',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='event',
            name='description',
            field=models.CharField(blank=True, max_length=280),
        ),
    ]
