# Generated by Django 2.2 on 2019-05-19 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_auto_20190519_0237'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='icon',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='person',
            name='icon',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=''),
        ),
    ]
