# Generated by Django 2.2.1 on 2019-05-18 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_auto_20190518_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='skills',
            field=models.ManyToManyField(blank=True, to='App.Skill'),
        ),
    ]
