# Generated by Django 2.2.1 on 2019-05-18 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_auto_20190518_1836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='organizers_volunteers',
            field=models.ManyToManyField(blank=True, to='App.Person'),
        ),
        migrations.AlterField(
            model_name='event',
            name='tags',
            field=models.ManyToManyField(blank=True, to='App.Tag'),
        ),
    ]
