# Generated by Django 2.2.1 on 2019-05-18 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_auto_20190518_1836'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='minimun_karma',
            new_name='mininun_karma',
        ),
    ]
